title: deliverybot
description: >-
  The missing build pipeline for GitHub Actions
long_description: >-
  Fast, safe and secure Continous Delivery pipelines you can setup in minutes.
  Powered by open source.

twitter:
  username: deliverybotdev
  card: summary
logo: /assets/logo.png
image: /assets/logo.png
author:
  twitter: deliverybotdev
social:
  name: Deliverybot
  links:
    - https://twitter.com/deliverybotdev

deliverybot_url: https://app.deliverybot.dev
github_app_url: https://github.com/apps/deliverybot
github_org_url: https://github.com/deliverybot
spectrum_url: https://spectrum.chat/deliverybot/general
start_url: /docs/quickstart/
slack_url: https://app.deliverybot.dev/slack/install
pricing_url: /pricing
twitter_url: https://twitter.com/deliverybotdev

terms_url: /terms/terms
privacy_url: /terms/privacy
security_url: /terms/security

privacy_email: privacy@pipelinebot.com
support_email: support@pipelinebot.com
security_email: security@pipelinebot.com
corp_name: Deliverybot
service_name: Deliverybot

baseurl: ""
url: https://deliverybot.dev
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: pretty
highlighter: rouge

plugins:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
